coderadar.game:
  levels:
    - level: 1
      neededPoints: 0
      pointsForLevelUp: 100
    - level: 2
      neededPoints: 100
      pointsForLevelUp: 120
    - level: 3
      neededPoints: 220
      pointsForLevelUp: 150
    - level: 4
      neededPoints: 370
      pointsForLevelUp: 190
    - level: 5
      neededPoints: 560
      pointsForLevelUp: 240
    - level: 6
      neededPoints: 800
      pointsForLevelUp: 300
    - level: 6
      neededPoints: 1100
      pointsForLevelUp: 370
